### ISSUE TITLE
Предлогаю перейти на jansson

### ISSUE THREAD

**Issue by ghost** [bcskda/2ch-cli#10]
Недавно разрабатывал одну программу, где понадобился json парсер. Попробовал json-c, но как по мне, он так себе из-за документации. Попробовал jansson, вполне удобно. Чтобы научиться писать с ним, можно прочитать у них пример и прочесть их доку по их API. Работает сносно.

**Comment by bcskda** [comment]
Посмотри последние коммиты в [original/0.4](https://github.com/bcskda/2ch-cli/tree/0.4), начиная с f4347f0ad03724bc4e2a0a8a0d3d3c0e92bd945c всё переписано на jsoncpp. С ней писать довольно просто, вроде даже шустро. И в репах (минимум гентушных) она есть в стабильной версии.

UPD: Или ты предлагаешь заменить им jsoncpp?

**Comment by ghost** [comment]
А, окей. Тогда думаю менять не надо.

**Comment by bcskda** [comment]
Хорошо
