### ISSUE TITLE
Не собирается под рачем (gcc 7.1.1 20170528, jsoncpp 1.8.0)

### ISSUE THREAD

**Issue by saber-nyan** [bcskda/2ch-cli#11]
Сначала ничего не менял, просто скачал и попытался собрать:
![2ch-cli_1](https://cloud.githubusercontent.com/assets/25345196/26732247/99148f78-47bf-11e7-836d-891b1933c8f3.png)
Ладно, не работает, ищу хедеры jsoncpp:
![2ch-cli_2](https://cloud.githubusercontent.com/assets/25345196/26732273/b26bd724-47bf-11e7-884e-3ac4c33b5917.png)
Редактирую:
![2ch-cli_3](https://cloud.githubusercontent.com/assets/25345196/26732290/c52b1cbc-47bf-11e7-9f26-d7822c407660.png)
Пытаюсь собрать с ними... и нихуя:
![2ch-cli_4](https://cloud.githubusercontent.com/assets/25345196/26732316/e1503242-47bf-11e7-9164-f9788256b2f3.png)
Полный лог:
https://gist.github.com/saber-nyan/32d87ecd35f72002d1b0b749e89ce3b1

**Comment by bcskda** [comment]
На какой ветке? Похоже, что на master.
Сорян, рабочая версия в 0.4, а README.md в мастере по ряду причин некорректен. Попробуй собрать 0.4. Ридми исправлю.

**Comment by ghost** [comment]
Ошибка явно на стороне системы, а не программы, проверь стабильность своих пакетов, а в особенности glibc и gcc.

**Comment by bcskda** [comment]
Дело не в системе, 100% не та ветка. Сделай ```git checkout 0.4```.

**Comment by ghost** [comment]
Ветка та, я даже повторил, всё то же самое. Проверил на компиляции, и правда не работает.
/usr/include/stdio.h:942:1: помилка: expected declaration before ‘}’ token

**Comment by bcskda** [comment]
Слака (и, видимо, арч) ставят jsoncpp не туда же, куда его ставят дебиан, убунта и гента - [см. тут](https://github.com/Sude-/lgogdownloader/issues/57). Надо опакетить, а то цирк какой-то.

**Comment by saber-nyan** [comment]
Пишет, что уже на "0.4". Куда симлинк-то сделать?

**Comment by ghost** [comment]
Не, @bcskda, дело явно в твоём коде, надо будет посмотреть.

**Comment by ghost** [comment]
Одна бага:
`#include <json.h>
#include <jsoncpp/json/json.h>`
Два подключения.

**Comment by bcskda** [comment]
Видел уже, поправлю. Может, починит ту гадость с stdio.h.
Но все равно надо запилить autoconf, раз такая разница в дистрах.

**Comment by saber-nyan** [comment]
Может, CMake? Он, вроде, попроще.

**Comment by bcskda** [comment]
Может, надо будет почитать.

@Reedych, когда поправлю хедеры, запилишь мейкфайл с учетом положения либ?

**Comment by saber-nyan** [comment]
Попробовал с CMake. Сразу скомпилировалось, но сыпятся ошибки линкера; я загуглил, пишут, что нельзя реализовывать переменные и функции в хедерах (как _error.h_, например).
Олсо, моя IDE говорит, что в этом же _error.h_ пропущена case _ERR_GENERAL_FORMAT:_ и еще несколько проблем в проекте.

Вот сам файл, кстати: https://gist.github.com/saber-nyan/9c8df816009bdc8947bc8691d1be8067
Гораздо лучше обычного Makefile выглядит...

**Comment by bcskda** [comment]
Сделаю в хэдэрах с *extern*. Функции перекинул в *\*.c*.
Создашь пулл-реквест с CMakeLists.txt? Не очень правильно было бы копипастить у тебя и коммитить.

**Comment by ghost** [comment]
Как этого можно было не знать?

**Comment by saber-nyan** [comment]
Ну ты закоммить сначала, потом у себя проверю и PR создам.

**Comment by saber-nyan** [comment]
Ну, пока так: https://github.com/bcskda/2ch-cli/pull/12

**Comment by bcskda** [comment]
Исправлено https://github.com/bcskda/2ch-cli/pull/12
