### ISSUE TITLE
Слишком высокий cmake_minimum_required

### ISSUE THREAD

**Issue by ghost** [bcskda/2ch-cli#13]
В CMakeLists слишком высокий cmake_minimum_required. Собрал с cmake 3.5.2 - работает.
В системе только 3.5.2.

**Comment by bcskda** [comment]
Посмотрю по докам cmake, на ближайшее время поставлю в master 3.5.2

**Comment by ghost** [comment]
А он постить уже умеет?

**Comment by bcskda** [comment]
Да, после загрузки по ```h``` выведет инфу по клавишам.

Заодно добавлю это в readme.

**Comment by bcskda** [comment]
Сделал в 325eec00c52179961d7277e2c6cdb66b134b5a30
