### ISSUE TITLE
Перенести логгирование в stderr

### ISSUE THREAD

**Issue by ghost** [bcskda/2ch-cli#2]
Мне кажется лучше логгировать традиционно в stdout/stderr, а не в log/.

**Comment by bcskda** [comment]
В stderr придется писать, кому какая запись принадлежит. Не то чтобы плохо, просто лишний объём, тем более если его не перенаправить в файл - поедет ncurses. Попробую, может правда будет лучше

**Comment by bcskda** [comment]
Перенесу, когда можно будет уменьшить объём логов - сейчас каждый по 200+ кб, многовато в один файл будет

**Comment by bcskda** [comment]
Сделал в dfe706ccbbec842029dba2313693f0befbe87c0e
