### ISSUE TITLE
Не въеду как поставить этот libjson

### ISSUE THREAD

**Issue by ghost** [bcskda/2ch-cli#9]
Как поставить его?

**Comment by bcskda** [comment]
ЕМНИП,
```
$ git clone https://github.com/vincenthz/libjson
$ cd libjson
$ make
# make install
```
Напишу точнее чуть позже

**Comment by pinkierton** [comment]
Ты не к тому libjson привязался. Нужно к этому https://github.com/json-c/json-c - этот настоящий и есть в репах.

**Comment by bcskda** [comment]
Угу, слишком поздно понял. В 0.5 буду чинить.
Спасибо

**Comment by ghost** [comment]
json-c хотябы в репах есть.

**Comment by bcskda** [comment]
Да, посмотрел сейчас. К следующему релизу перепишу под либу из реп, пусть будет 0.4 уже рабочая pre.

**Comment by ghost** [comment]
Просто эту библиотеку надо как-то подтянуть, а читать маны по линковке лень. Ну ок, 0.4 будет бетой.

**Comment by bcskda** [comment]
Что ```make install``` выводил?

**Comment by ghost** [comment]
Что типо перетащил свои .so-шни, .a, .pc, .h. Но не подтянулся, я потом сам разберусь.

**Comment by bcskda** [comment]
Окей

**Comment by ghost** [comment]
Вообще я дурак, что не предупредил, что лучше использовать json-c (он у многих вместе с pulseaudio 9.0 есть).

**Comment by bcskda** [comment]
Ну да, посмотрел уже
Она более замороченная, к 0.5 тогда переведу
